### ISSUE TITLE
[Bug]: AssertionError: Bad value for setting upcast_attn: False; expecting str

### ISSUE THREAD

**Issue by TheStarBoys** [brkirch/stable-diffusion-webui#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

An error occurred when changing settings. It shows "AssertionError: Bad value for setting upcast_attn: False; expecting str". If we don't even do any change and just click "apply settings" button, the same error also occurs.

### Steps to reproduce the problem

If we don't even do any change and just click "apply settings" button, the same error also occurs.

### What should have happened?

settings applied.

### Commit where the problem happens

1e30ae895e4

### What platforms do you use to access the UI ?

MacOS

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--disable-nan-check --skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
```

### List of extensions

no

### Console logs

```Shell
Error completing request
Arguments: (True, 'png', '', True, True, 'png', False, True, False, -1, True, False, False, False, False, False, False, 80, False, True, 4.0, 4000.0, 200.0, True, False, True, False, '', False, '', 'outputs/txt2img-images', 'outputs/img2img-images', 'outputs/extras-images', '', 'outputs/txt2img-grids', 'outputs/img2img-grids', 'log/images', 'outputs/init-images', True, True, False, '[date]', 8, 192, 8, ['R-ESRGAN 4x+', 'R-ESRGAN 4x+ Anime6B'], None, 256, 8, 100, False, 192, 8, 'CodeFormer', 0.5, False, False, 8, False, True, False, False, False, False, True, '', ' ', 1, 500.0, False, False, False, 120.0, None, 0, 0, 'Automatic', True, 1, 1, False, False, '#ffffff', False, True, True, 20, 1, False, 'GPU', False, False, False, False, False, False, False, 1, 24, 48, 1500.0, [], 0.5, True, False, True, '', 'cards', 1, 0.0, 0.0, ' ', 'None', 'None', True, False, False, False, True, True, True, True, True, '', True, True, True, True, True, 0.1, 0.05, '.,\\/!?%^*;:{}=`~()', 'sd_model_checkpoint', [], 'inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts', '', 'None', 'Default', True, True, True, 10, 'Approx NN', 'Prompt', 1000.0, [], 0, 1, 'uniform', 0, 0, 0, 1, 0, False, 'bh1', 'time_uniform', 3, True, [], [], 5, None, None, None, None, False, 'txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others', [], True, False, False, True, True, '0 - none', True, True, False, False, True, False, 6.0, 6.0, 20.0, False, 200.0, False, True, 'aesthetic_score', True) {}
Traceback (most recent call last):
  File "/Users/thestar/Development/ai/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Users/thestar/Development/ai/stable-diffusion-webui/modules/ui.py", line 1493, in run_settings
    assert comp == dummy_component or opts.same_type(value, opts.data_labels[key].default), f"Bad value for setting {key}: {value}; expecting {type(opts.data_labels[key].default).__name__}"
AssertionError: Bad value for setting upcast_attn: False; expecting str
```

**Comment by YitziG** [comment]
Same issue
