### ISSUE TITLE
[Bug]: deforum ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by yourbartender** [brkirch/stable-diffusion-webui#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

after first updating and then with a clean new install deforum went missing. I've updated it, removed it, installed anew and on a new clean install, and I keep getting error deforum ModuleNotFoundError: No module named 'rich'. Ive installed rich with pip and python -pip, no help.

### Steps to reproduce the problem

1. install 1.1.1
2. install deforum extension
3. start up webui, errors pop up, no extension loaded

### What should have happened?

Rich should be recognized, deforum tab should show up

### Commit where the problem happens

1e30ae895e487b1b4b81033db14863c702d26268

### What platforms do you use to access the UI ?

MacOS

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
No
```

### List of extensions

deforum

### Console logs

```Shell
Launching Web UI with arguments: --autolaunch --skip-torch-cuda-test --skip-install --no-download-sd-model --no-half-vae --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Error loading script: deforum.py
Traceback (most recent call last):
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 22, in <module>
    init_deforum()
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 14, in init_deforum
    from deforum_helpers.ui_right import on_ui_tabs
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/ui_right.py", line 1, in <module>
    from .args import DeforumOutputArgs, get_component_names, get_settings_component_names
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/args.py", line 11, in <module>
    from .deforum_controlnet import controlnet_component_names
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/deforum_controlnet.py", line 13, in <module>
    from .video_audio_utilities import vid2frames, convert_image
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/video_audio_utilities.py", line 15, in <module>
    from .rich import console
  File "/Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/rich.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

Loading weights [d635794c1f] from /Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/models/Stable-diffusion/512-base-ema.ckpt
Creating model from config: /Users/tknuutil/AIstuff/m1webui/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/configs/stable-diffusion/v2-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying sub-quadratic cross attention optimization.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
Textual inversion embeddings loaded(1): retrofutur
Textual inversion embeddings skipped(7): b_w, bad_prompt_version2, bad-hands-5, retro-girl, kkw-medieval, abstract_geometric_splash_v1, southofthebordersd15
Model loaded in 17.2s (load weights from disk: 2.8s, find config: 5.4s, create model: 0.1s, apply weights to model: 4.1s, apply half(): 2.5s, load VAE: 0.2s, move model to device: 0.8s, load textual inversion embeddings: 1.3s).
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 22.4s (import torch: 0.9s, import gradio: 0.6s, import ldm: 0.3s, other imports: 1.7s, load scripts: 0.4s, load SD checkpoint: 17.7s, create ui: 0.4s, gradio launch: 0.3s).
```

### Additional information

If there is a version I should downgrade (deforum), let me know :)

**Comment by novitae** [comment]
do `pip install rich`

**Comment by codepainter** [comment]
I encountered the same thing but with `adetailer`

I fixed it with ```./venv/bin/python -m pip install rich```. Run it from webui's root folder.

**Comment by fckbauer** [comment]
> I encountered the same thing but with `adetailer`
> 
> I fixed it with `./venv/bin/python -m pip install rich`. Run it from webui's root folder.

i did what you said, now it's looking for module "media pipe" .   Do i also need to install that manually? thanks also wanting to try adetailer. thank you

**Comment by fckbauer** [comment]
I was able to manually install everything, now adetailer works! thanks a bunch. just a question, does the same work for roop? I haven't had the chance to manually install every module that it says missing coz i know that it needs Visual Studio. Thanks!

**Comment by batsteek** [comment]
./venv/bin/python -m pip install rich
./venv/bin/python -m pip install mediapipe
./venv/bin/python -m pip install ultralytics

**Comment by Infiexe** [comment]
Same here, extensions don't load their depedencies
