### ISSUE TITLE
[Bug]: Latest MacOS update broke downloading extensions through app

### ISSUE THREAD

**Issue by Spaceturtle7** [brkirch/stable-diffusion-webui#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to download an extension through the app doesn't work. It won't download. 

### Steps to reproduce the problem

1. Go to "Extensions" tab
2. Go to "Available" tab
3. Click "Load from:"
4. Select install on any displayed extensions
5. Timeout error

### What should have happened?

Extension should have installed.

### Sysinfo

[sysinfo-2023-09-28-05-54.txt](https://github.com/brkirch/stable-diffusion-webui/files/12746076/sysinfo-2023-09-28-05-54.txt)

### Console logs

```Shell
Last login: Wed Sep 27 22:47:32 on ttys000
screen -c /tmp/stable-diffusion-webui-screenrc -L '/Applications/Stable Diffusion Web UI.app/Contents/Resources/Start Web UI.sh';exit
Name@Name ~ % screen -c /tmp/stable-diffusion-webui-screenrc -L '/Applications/Stable Diffusion Web UI.app/Contents/Resources/Start Web UI.sh';exit









































                                                                   

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on Name user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.13 (main, Sep  4 2023, 20:22:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: 20230919_experimental
Commit hash: db9cdd8fd96e424dc53a4fe16ef1095595d10725
Launching Web UI with arguments: --data-dir /Users/Name/Documents/Stable Diffusion Web UI --electron --electron-path /Applications/Stable Diffusion Web UI.app/Contents/MacOS/Electron --electron-quit-on-exit --skip-torch-cuda-test --skip-install --no-half-vae --upcast-sampling --precision full
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
2023-09-27 22:47:36,904 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: /Users/Name/Documents/Stable Diffusion Web UI/extensions/sd-webui-controlnet/annotator/downloads
2023-09-27 22:47:36,947 - ControlNet - INFO - ControlNet v1.1.410
Loading weights [821628644e] from /Users/Name/Documents/Stable Diffusion Web UI/models/Stable-diffusion/EasyFluffV11.2.safetensors
Creating model from config: /Users/Name/Documents/Stable Diffusion Web UI/models/Stable-diffusion/EasyFluffV11.2.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 4.6s (prepare environment: 1.0s, import torch: 1.3s, import gradio: 0.3s, setup paths: 0.4s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 0.4s, initialize extra networks: 0.2s, create ui: 0.3s).
2023-09-27 22:47:37.675 Electron[2245:148285] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Applying attention optimization: sub-quadratic... done.
Model loaded in 3.8s (load weights from disk: 0.2s, create model: 1.0s, apply weights to model: 0.5s, apply dtype to VAE: 0.8s, move model to device: 0.1s, calculate empty prompt: 1.2s).
*** Error completing request
*** Arguments: ('', 'https://github.com/Seshelle/CFG_Rescale_webui', '') {}
    Traceback (most recent call last):
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 385, in install_extension_from_url
        raise err
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 377, in install_extension_from_url
        os.rename(tmpdir, target_dir)
    TimeoutError: [Errno 60] Operation timed out: '/Users/Name/Documents/Stable Diffusion Web UI/tmp/CFG_Rescale_webui' -> '/Users/Name/Documents/Stable Diffusion Web UI/extensions/CFG_Rescale_webui'

---
*** Error completing request
*** Arguments: ('', 'https://github.com/Seshelle/CFG_Rescale_webui', '') {}
    Traceback (most recent call last):
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 385, in install_extension_from_url
        raise err
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 377, in install_extension_from_url
        os.rename(tmpdir, target_dir)
    TimeoutError: [Errno 60] Operation timed out: '/Users/Name/Documents/Stable Diffusion Web UI/tmp/CFG_Rescale_webui' -> '/Users/Name/Documents/Stable Diffusion Web UI/extensions/CFG_Rescale_webui'

---
*** Error completing request
*** Arguments: ('https://github.com/adieyal/sd-dynamic-prompts.git', ['ads', 'localization', 'installed'], 0, 'dynamic pr') {}
    Traceback (most recent call last):
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 397, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 385, in install_extension_from_url
        raise err
      File "/Applications/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/ui_extensions.py", line 377, in install_extension_from_url
        os.rename(tmpdir, target_dir)
    TimeoutError: [Errno 60] Operation timed out: '/Users/Name/Documents/Stable Diffusion Web UI/tmp/sd-dynamic-prompts' -> '/Users/Name/Documents/Stable Diffusion Web UI/extensions/sd-dynamic-prompts'

---
```

### Additional information

MacOS, Sonoma 14.0, Apple M2 Max. Running through app. Same error for trying to install through URL. Extensions installed manually work and function normally.

**Comment by Spaceturtle7** [comment]
Seems installing the application through the installer fixed the issue.

**Comment by Spaceturtle7** [comment]
Installing the application through the installer has fixed the issue.

**Comment by Spaceturtle7** [comment]
It has come back, same error

**Comment by Spaceturtle7** [comment]
It has come back, same error
